In [9]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Input
import numpy as np


In [6]:
model = Sequential(
    [
        Input(shape=(2,)),
        Dense(2, activation="linear"),
        Dense(1, activation="linear")
    ]
)

In [7]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[ 0.09583712, -0.8051983 ],
        [ 0.2901839 , -0.8587135 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.69964844],
        [-0.58136755]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [
    np.array([[0.1, 0.1],
              [0.1, 0.1]], dtype=np.float32),   # W1 — shape (2,2)
    np.array([0., 0.], dtype=np.float32),        # b1 — shape (2,)
    np.array([[0.1],
              [0.1]], dtype=np.float32),          # W2 — shape (2,1)
    np.array([0.], dtype=np.float32)             # b2 — shape (1,)
]

model.set_weights(new_weights)